---
title: Julia-build
email: mark@taqtiqa.com
description: > # this means to ignore newlines until next element
  Build and install multiple versions of <a href="https://www.julialang.org/">Julia</a>.
github_username:  jlenv
include_related_posts: true
plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
relative_links:
  enabled: true
  collections: true
remote_theme: pmarsceill/just-the-docs
